// This is an autogenerated file, please refrain from changing it
//
//
//----------------------------------------------------------------------------
//   The confidential and proprietary information contained in this file may
//   only be used by a person authorised under and to the extent permitted
//   by a subsisting licensing agreement from ARM Limited or its affiliates.
//
//          (C) COPYRIGHT 2013 - 2018 ARM Limited or its affiliates
//              ALL RIGHTS RESERVED
//
//   This entire notice must be reproduced on all copies of this file
//   and copies of this file may only be made by a person if such person is
//   permitted to do so under the terms of a subsisting license agreement
//   from ARM Limited or its affiliates.
//----------------------------------------------------------------------------
#ifndef __ACT_SERVER__VERSION_H
#define __ACT_SERVER__VERSION_H

#define __MODULE_VERSION     "3.5.1"
#define __COPYRIGHT_INYR     "2013"
#define __COPYRIGHT_YEAR     "2018"
#define __SOURCE_DATE_TIME   "2018-01-10 15:58:59 +0000"

#endif // __ACT_SERVER__VERSION_H
