#
# autogenerated makefile
# please do not edit
#

override GCC_FLAGS += $(addprefix -I../libevent/,include target/build/include)
override GXX_FLAGS += $(addprefix -I../libevent/,include target/build/include)

